In [73]:
import numpy as np
import pandas as pd

In [16]:
#Dataframe 二维数组
d = {'name':['Jack','Tom','Janny'],
    'age':[18,19,13],
    'gender':['a','b','c']}
f = pd.DataFrame(d)
print(f,type(f))
# index行标签 columns列标签
print(f.index,'\n数据类型为：',type(f.index))
print(f.columns,type(f.columns))
print(f.values,type(f.values))


    name  age gender
0   Jack   18      a
1    Tom   19      b
2  Janny   13      c <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1) 
数据类型为： <class 'pandas.core.indexes.range.RangeIndex'>
Index(['name', 'age', 'gender'], dtype='object') <class 'pandas.core.indexes.base.Index'>
[['Jack' 18 'a']
 ['Tom' 19 'b']
 ['Janny' 13 'c']] <class 'numpy.ndarray'>


In [11]:
#由数组list组成的字典创建
data1 = {'a':[1,2,3],
        'b':[4,5,6],
        'c':[7,8,9]} #key就是列名
print(data1)
d1 = pd.DataFrame(data1, index = ['a','b','c'])
print(d1)

{'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}
   a  b  c
a  1  4  7
b  2  5  8
c  3  6  9


In [10]:
#由数组 组成的字典创建
data2 = {'one':np.random.rand(3),
        'two':np.random.rand(3)}
print(data2)
d2 = pd.DataFrame(data2)
print(d2)

{'one': array([0.83413524, 0.95156078, 0.95080614]), 'two': array([0.41606603, 0.2542471 , 0.95293961])}
        one       two
0  0.834135  0.416066
1  0.951561  0.254247
2  0.950806  0.952940


In [9]:
#由Series组成的字典创建
data3 = {'one':pd.Series(np.random.rand(3)),
         'two':pd.Series(np.random.rand(4))} #没有设置index的series
d1 = pd.DataFrame(data3)
print(d1)
#长度可以不一样，会生成空值NaN

        one       two
0  0.492403  0.197333
1  0.855147  0.911333
2  0.045671  0.408308
3       NaN  0.183352


In [20]:
#设置了index的series
data4 = {'a':pd.Series(np.random.rand(3),index = ['a','b','c']),
         'b':pd.Series(np.random.rand(4),index = ['a','b','c','d'])} #有共同的index会自动对齐
print(data4)
print(pd.DataFrame(data4))

{'a': a    0.279846
b    0.289914
c    0.029839
dtype: float64, 'b': a    0.751211
b    0.135308
c    0.918692
d    0.734693
dtype: float64}
          a         b
a  0.279846  0.751211
b  0.289914  0.135308
c  0.029839  0.918692
d       NaN  0.734693


In [22]:
#通过二维数组直接创建，常用
ar = np.random.rand(16).reshape(4,4) #index,columns默认
print(ar)
print(pd.DataFrame(ar))

[[0.66447704 0.80698718 0.92179756 0.50504419]
 [0.51834952 0.84219159 0.53005625 0.55335233]
 [0.4153064  0.33702453 0.00766681 0.917189  ]
 [0.54536173 0.94748959 0.99710074 0.64999799]]
          0         1         2         3
0  0.664477  0.806987  0.921798  0.505044
1  0.518350  0.842192  0.530056  0.553352
2  0.415306  0.337025  0.007667  0.917189
3  0.545362  0.947490  0.997101  0.649998


In [24]:
#设置行标签，列标签
ar2 = np.random.rand(16).reshape(4,4)
d2 = pd.DataFrame(ar2,
                  index = ['a','b','c','d'],
                  columns = ['one','two','three','four'])
print(d2)

        one       two     three      four
a  0.719001  0.794373  0.667958  0.712699
b  0.246288  0.672952  0.210079  0.941474
c  0.545239  0.796584  0.387507  0.428865
d  0.967464  0.576862  0.883373  0.026256


In [34]:
#由字典组成的列表创建
data = [{'a':1,'b':3,'c':5},{'a':4,'c':6}]
print(data)
print(pd.DataFrame(data))
df1 = pd.DataFrame(data,index = ['one','two'])
print(df1)
df2 = pd.DataFrame(data,columns = ['a','c'])
print(df2)
#每个字典就是一行

[{'a': 1, 'b': 3, 'c': 5}, {'a': 4, 'c': 6}]
   a    b  c
0  1  3.0  5
1  4  NaN  6
     a    b  c
one  1  3.0  5
two  4  NaN  6
   a  c
0  1  5
1  4  6


In [42]:
#由字典组成的嵌套字典创建
data = {'Marry':{'Math':85,'English':90,'Chinese':98},
       'Tom':{'Math':87,'English':80,'Chinese':78},
       'Tony':{'Math':97,'English':85,'Chinese':88}}
print(data)
df1 = pd.DataFrame(data)
print(df1)
df2 = pd.DataFrame(data,columns = ['Tom','Tony','Nana'])
print(df2)

{'Marry': {'Math': 85, 'English': 90, 'Chinese': 98}, 'Tom': {'Math': 87, 'English': 80, 'Chinese': 78}, 'Tony': {'Math': 97, 'English': 85, 'Chinese': 88}}
         Marry  Tom  Tony
Chinese     98   78    88
English     90   80    85
Math        85   87    97
         Tom  Tony Nana
Chinese   78    88  NaN
English   80    85  NaN
Math      87    97  NaN


In [57]:
#索引
#选择列
data8 = pd.DataFrame(np.random.rand(12).reshape(3,4),
                     index = ['one','two','three'],
                    columns = ['a','b','c','d'])
print(data8)
print(data8['a'])
print(data8[['a','b']])

d1 = data8['a'] #Series的格式
d2 = data8[['a','b']]
print(d1,type(d1))

print(d2,type(d2))
#列显示字段，行显示哪些数据

              a         b         c         d
one    0.969503  0.919556  0.496090  0.673654
two    0.824367  0.596875  0.248204  0.785938
three  0.328655  0.045354  0.383566  0.038233
one      0.969503
two      0.824367
three    0.328655
Name: a, dtype: float64
              a         b
one    0.969503  0.919556
two    0.824367  0.596875
three  0.328655  0.045354
one      0.969503
two      0.824367
three    0.328655
Name: a, dtype: float64 <class 'pandas.core.series.Series'>
              a         b
one    0.969503  0.919556
two    0.824367  0.596875
three  0.328655  0.045354 <class 'pandas.core.frame.DataFrame'>


In [62]:
#选择行
d3 = data8.loc['one'] #location
d4 = data8.loc[['one','two']]
d5 = data8.loc['one': 'three'] #切片索引
d6 = data8[:1] #切片可以选择行
print(d3,type(d3))
print(d4,type(d4))
print(d5)
print(d6)


a    0.969503
b    0.919556
c    0.496090
d    0.673654
Name: one, dtype: float64 <class 'pandas.core.series.Series'>
            a         b         c         d
one  0.969503  0.919556  0.496090  0.673654
two  0.824367  0.596875  0.248204  0.785938 <class 'pandas.core.frame.DataFrame'>
              a         b         c         d
one    0.969503  0.919556  0.496090  0.673654
two    0.824367  0.596875  0.248204  0.785938
three  0.328655  0.045354  0.383566  0.038233
            a         b        c         d
one  0.969503  0.919556  0.49609  0.673654


In [68]:
#按整数位置索引
d7 = data8.iloc[:2]
d8 = data8.iloc[[0,2]]
d9 = data8.iloc[::2] #步长为2
print(d7)
print(d8)
print(d9)

            a         b         c         d
one  0.969503  0.919556  0.496090  0.673654
two  0.824367  0.596875  0.248204  0.785938
              a         b         c         d
one    0.969503  0.919556  0.496090  0.673654
three  0.328655  0.045354  0.383566  0.038233
              a         b         c         d
one    0.969503  0.919556  0.496090  0.673654
three  0.328655  0.045354  0.383566  0.038233


In [72]:
data9 = pd.DataFrame(np.random.rand(12).reshape(3,4)*100,
                     index = ['one','two','three'],
                    columns = ['a','b','c','d'])
print(data9[data9<50][['a','b']]) #布尔值的索引

              a          b
one    4.244194        NaN
two         NaN  21.157575
three       NaN  42.533616


In [84]:
#数据查看
df = pd.DataFrame(np.random.rand(36).reshape(6,6)*100,
                 columns = ['a','b','c','d','e','f'])
print(df.head(2)) #读取前2行
print(df.head()) #默认读取前5行
print(df.tail(3)) #读取倒数3行

           a          b          c          d          e          f
0  61.059958   2.601107  48.169008  38.026860  32.622278  80.010640
1  32.222679  28.331568  54.647430  38.435695  55.100053  13.688527
           a          b          c          d          e          f
0  61.059958   2.601107  48.169008  38.026860  32.622278  80.010640
1  32.222679  28.331568  54.647430  38.435695  55.100053  13.688527
2  90.186129   3.610997  13.142555  38.053479  78.520262  98.375332
3  13.707661  16.760155  84.809958  36.634964  14.255557  90.344752
4  99.870039   2.514177  85.625165  21.982258  97.600438  19.704403
           a          b          c          d          e          f
3  13.707661  16.760155  84.809958  36.634964  14.255557  90.344752
4  99.870039   2.514177  85.625165  21.982258  97.600438  19.704403
5  17.765865  51.894778  45.734802   4.398644   1.043791  36.537358


In [89]:
#转置
df = pd.DataFrame(np.random.rand(12).reshape(4,3),
                 columns =['a','b','c'])
print(df)
print(df.T)

          a         b         c
0  0.970965  0.084652  0.028446
1  0.419273  0.483627  0.173832
2  0.135207  0.892209  0.724717
3  0.274211  0.554758  0.004108
          0         1         2         3
a  0.970965  0.419273  0.135207  0.274211
b  0.084652  0.483627  0.892209  0.554758
c  0.028446  0.173832  0.724717  0.004108


In [106]:
#添加/修改
df = pd.DataFrame(np.random.rand(15).reshape(5,3)*100,
                  columns = ['a','b','c'])
print(df)
df['d'] = 10
print(df)

df['a'] = 10
df.loc[3] = 10
print(df)

df[['a','c']] = 10
print(df)

df.iloc[::2] = 101 #每格2个值
print(df)

df.iloc[1,3] = 66 #修改第2行第4列的值
print(df)

           a          b          c
0  59.921725  61.661040   0.237721
1  15.509540  38.513585  63.343545
2  39.498502   0.994082  75.118724
3  57.645440  69.170058   3.096471
4  54.315586  16.489683   8.590913
           a          b          c   d
0  59.921725  61.661040   0.237721  10
1  15.509540  38.513585  63.343545  10
2  39.498502   0.994082  75.118724  10
3  57.645440  69.170058   3.096471  10
4  54.315586  16.489683   8.590913  10
    a          b          c   d
0  10  61.661040   0.237721  10
1  10  38.513585  63.343545  10
2  10   0.994082  75.118724  10
3  10  10.000000  10.000000  10
4  10  16.489683   8.590913  10
    a          b   c   d
0  10  61.661040  10  10
1  10  38.513585  10  10
2  10   0.994082  10  10
3  10  10.000000  10  10
4  10  16.489683  10  10
     a           b    c    d
0  101  101.000000  101  101
1   10   38.513585   10   10
2  101  101.000000  101  101
3   10   10.000000   10   10
4  101  101.000000  101  101
     a           b    c    d
0  101  101

In [115]:
#del删除列 drop()删除行 改变原数据
df = pd.DataFrame(np.random.rand(24).reshape(6,4),
                 columns = ['a','b','c','d'])
print(df)

del df['a'] #删除列
print(df)

print(df.drop(0)) #删除某一行
print(df.drop([1,2])) #删除两行
print(df)

print(df.drop(['d'],axis = 1)) #drop删除列需要加 axis = 1

          a         b         c         d
0  0.303523  0.569139  0.090581  0.491177
1  0.636114  0.070523  0.982844  0.193331
2  0.867685  0.486970  0.513204  0.870943
3  0.928792  0.493228  0.912969  0.820501
4  0.556528  0.077212  0.186343  0.666177
5  0.448867  0.981104  0.611875  0.790552
          b         c         d
0  0.569139  0.090581  0.491177
1  0.070523  0.982844  0.193331
2  0.486970  0.513204  0.870943
3  0.493228  0.912969  0.820501
4  0.077212  0.186343  0.666177
5  0.981104  0.611875  0.790552
          b         c         d
1  0.070523  0.982844  0.193331
2  0.486970  0.513204  0.870943
3  0.493228  0.912969  0.820501
4  0.077212  0.186343  0.666177
5  0.981104  0.611875  0.790552
          b         c         d
0  0.569139  0.090581  0.491177
3  0.493228  0.912969  0.820501
4  0.077212  0.186343  0.666177
5  0.981104  0.611875  0.790552
          b         c         d
0  0.569139  0.090581  0.491177
1  0.070523  0.982844  0.193331
2  0.486970  0.513204  0.870943
3 

In [119]:
#对齐
df1 = pd.DataFrame(np.random.rand(24).reshape(6,4),
                  columns = ['a','b','c','d'])
print(df1)
df2 = pd.DataFrame(np.random.rand(15).reshape(5,3),
                  columns = ['a','b','c'])
print(df2)
print(df1+df2)

          a         b         c         d
0  0.298456  0.707518  0.625580  0.211512
1  0.991312  0.345730  0.951755  0.459303
2  0.990347  0.602283  0.593704  0.532188
3  0.891477  0.744209  0.875900  0.630914
4  0.046107  0.009885  0.622494  0.093538
5  0.199633  0.787754  0.974963  0.493680
          a         b         c
0  0.291623  0.267662  0.051092
1  0.002658  0.359728  0.807387
2  0.908258  0.019918  0.656827
3  0.222598  0.729508  0.273371
4  0.332612  0.508623  0.006475
          a         b         c   d
0  0.590078  0.975181  0.676672 NaN
1  0.993970  0.705457  1.759142 NaN
2  1.898604  0.622201  1.250530 NaN
3  1.114075  1.473717  1.149271 NaN
4  0.378719  0.518508  0.628969 NaN
5       NaN       NaN       NaN NaN


In [122]:
#排序 sort_values
df = pd.DataFrame(np.random.rand(24).reshape(6,4),
                 columns = ['a','b','c','d'])
print(df)
print(df.sort_values(['a'],ascending = True))  #升序,默认的(ascending升高的意思)
print(df.sort_values(['a'],ascending = False)) #降序
#单列排序

          a         b         c         d
0  0.175753  0.979781  0.377809  0.808286
1  0.209039  0.005989  0.145313  0.490079
2  0.761630  0.338166  0.826270  0.539370
3  0.517063  0.852164  0.745061  0.816197
4  0.719132  0.686007  0.141187  0.156538
5  0.324683  0.424249  0.535395  0.194151
          a         b         c         d
0  0.175753  0.979781  0.377809  0.808286
1  0.209039  0.005989  0.145313  0.490079
5  0.324683  0.424249  0.535395  0.194151
3  0.517063  0.852164  0.745061  0.816197
4  0.719132  0.686007  0.141187  0.156538
2  0.761630  0.338166  0.826270  0.539370
          a         b         c         d
2  0.761630  0.338166  0.826270  0.539370
4  0.719132  0.686007  0.141187  0.156538
3  0.517063  0.852164  0.745061  0.816197
5  0.324683  0.424249  0.535395  0.194151
1  0.209039  0.005989  0.145313  0.490079
0  0.175753  0.979781  0.377809  0.808286


In [127]:
#多列排序
df = pd.DataFrame({'a':[1,1,3,2,2,3],
                  'b':list(range(6)),
                  'c':list(range(6,0,-1))})
print(df)
print(df.sort_values(['a','b'])) #先排a，再在a里面排b（a得有一样的值，多列才有意义）

   a  b  c
0  1  0  6
1  1  1  5
2  3  2  4
3  2  3  3
4  2  4  2
5  3  5  1
   a  b  c
0  1  0  6
1  1  1  5
3  2  3  3
4  2  4  2
2  3  2  4
5  3  5  1
